<a href="https://colab.research.google.com/github/woodstone10/python-study/blob/main/Numpy_study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy study

---



In [1]:
import numpy as np

## List data -> Array data

In [2]:
data = [6, 7, 8, 0, 1] #list data
data

[6, 7, 8, 0, 1]

In [3]:
arr1 = np.array(data) #array data
arr1

array([6, 7, 8, 0, 1])

In [4]:
data2 = [ [1,2,3,4], [5,6,7,8]]
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [5]:
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
arr2.ndim

2

In [7]:
arr2.shape

(2, 4)

In [10]:
arr2.dtype

dtype('int64')

In [19]:
np.array([1,2,3,4,5], dtype=np.float32)

array([1., 2., 3., 4., 5.], dtype=float32)

In [20]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## scalar computation

(no for loop)

In [22]:
arr = np.array([ [1,2,3], [4,5,6]])
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [23]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [24]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [25]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr[5] #indexing

5

In [27]:
arr[5:8] #slicing

array([5, 6, 7])

In [28]:
arr[5:8]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [29]:
arr = np.array([ [1,2,3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
arr[1,0] #==arr[1][0]

4

In [32]:
arr[:2, 1:]

array([[2, 3],
       [5, 6]])

In [33]:
data = np.random.randn(7,4)
data

array([[ 1.31261643, -0.35928233,  2.13125264,  0.11385937],
       [ 1.19268152,  0.36198833, -1.57346425, -1.20460632],
       [ 1.45858889,  0.38325884,  1.57063541,  2.76095069],
       [-0.36864374,  0.35671719, -2.41254046,  0.61791254],
       [ 0.21417184,  0.58780718,  3.19109852, -0.21792252],
       [-1.00347088,  1.22039985, -1.18743115,  1.31409033],
       [ 0.10145314,  0.27115576,  0.92707221, -2.29943121]])

In [34]:
names = np.array(['a','b','c','d','e','f','g'])
names

array(['a', 'b', 'c', 'd', 'e', 'f', 'g'], dtype='<U1')

In [35]:
data[names=='a'] #indexing with boolean

array([[ 1.31261643, -0.35928233,  2.13125264,  0.11385937]])

In [36]:
data[names=='a',3]

array([0.11385937])

In [37]:
data[names=='a',2:]

array([[2.13125264, 0.11385937]])

In [39]:
arr = np.empty((8,4))
arr

array([[4.65942517e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [41]:
for i in range(8):
  arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [42]:
arr[[4]]

array([[4., 4., 4., 4.]])

In [43]:
arr[[-1]]

array([[7., 7., 7., 7.]])

In [44]:
arr[[4, -1]]

array([[4., 4., 4., 4.],
       [7., 7., 7., 7.]])

In [45]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [47]:
arr.reshape((4,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [51]:
arr2 = arr.reshape((2,4))
arr2

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [52]:
arr2.T

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

## universal functions

In [54]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [56]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [57]:
x = np.random.randn(8)
x

array([-0.35667083,  2.17909508, -0.28410555,  0.23815735,  0.62723748,
       -0.95429007,  1.14523461, -1.12603501])

In [58]:
y = np.random.randn(8)
y

array([ 0.57116186, -0.83813569,  0.27300112,  0.23050365,  1.38050276,
       -0.91002974,  1.04751485, -0.60954989])

In [63]:
np.maximum(x,y)

array([ 0.57116186,  2.17909508,  0.27300112,  0.23815735,  1.38050276,
       -0.91002974,  1.14523461, -0.60954989])

In [64]:
np.cos(x)

array([ 0.93706442, -0.57147221,  0.95991275,  0.97177433,  0.80965195,
        0.57818814,  0.41283247,  0.43024243])

In [69]:
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [70]:
y = np.array([11,12,13,14,15])
y

array([11, 12, 13, 14, 15])

In [71]:
cond = np.array([True,False,True,True,False])
cond

array([ True, False,  True,  True, False])

zip and where

In [72]:
result = [ (x1 if c1 else y1) for x1, y1, c1 in zip(x,y,cond) ]
result

[1, 12, 3, 4, 15]

In [73]:
result2 = np.where(cond,x,y)
result2

array([ 1, 12,  3,  4, 15])

In [74]:
result2 = np.where(cond==True,x,y)
result2

array([ 1, 12,  3,  4, 15])

In [75]:
result2 = np.where(cond==False,x,y)
result2

array([11,  2, 13, 14,  5])

In [76]:
result2 = np.where(x>2,cond,y)
result2

array([11, 12,  1,  1,  0])

Math and Statistic

In [77]:
arr = np.random.randn(5,4)
arr

array([[-0.66018612, -0.4866443 ,  1.68381173, -0.17950533],
       [-1.22228239, -1.31398164,  1.42196432, -1.20440497],
       [-0.68768292, -1.00073954,  1.35919399,  0.41786696],
       [-1.67608928, -0.24696329, -0.40672049,  0.04745844],
       [-0.04083725, -0.45209496, -0.84348274, -0.27822747]])

In [78]:
arr.mean()

-0.28847736321832007

In [79]:
np.mean(arr)

-0.28847736321832007

In [80]:
arr.sum()

-5.769547264366402

In [81]:
arr.mean(axis=0) #X-axis

array([-0.85741559, -0.70008475,  0.64295336, -0.23936248])

In [82]:
arr.mean(axis=1) #Y-axis

array([ 0.08936899, -0.57967617,  0.02215962, -0.57057865, -0.40366061])

In [93]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [94]:
arr.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [95]:
arr.cumprod()

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800])

In [96]:
arr.sum()

55

In [98]:
arr.any()

True

In [99]:
arr.all()

True

In [104]:
arr = np.random.randn(5,4)
arr

array([[ 0.38459922, -0.68498917, -0.00942674,  2.04921444],
       [ 1.09931672, -1.27906299, -1.5552042 , -0.84527859],
       [ 0.18727773,  2.00015059,  0.86821868, -0.9387164 ],
       [ 0.14583788,  0.09834803,  0.03953923, -0.77396206],
       [-1.45328074, -0.19950556,  0.51258435, -0.1970348 ]])

In [105]:
arr[(arr>2).any()]

array([[[ 0.38459922, -0.68498917, -0.00942674,  2.04921444],
        [ 1.09931672, -1.27906299, -1.5552042 , -0.84527859],
        [ 0.18727773,  2.00015059,  0.86821868, -0.9387164 ],
        [ 0.14583788,  0.09834803,  0.03953923, -0.77396206],
        [-1.45328074, -0.19950556,  0.51258435, -0.1970348 ]]])

In [108]:
arr[(arr>2).any(axis=1)]

array([[ 0.38459922, -0.68498917, -0.00942674,  2.04921444],
       [ 0.18727773,  2.00015059,  0.86821868, -0.9387164 ]])

In [110]:
arr.sort(axis=0)
arr

array([[-1.45328074, -1.27906299, -1.5552042 , -0.9387164 ],
       [ 0.14583788, -0.68498917, -0.00942674, -0.84527859],
       [ 0.18727773, -0.19950556,  0.03953923, -0.77396206],
       [ 0.38459922,  0.09834803,  0.51258435, -0.1970348 ],
       [ 1.09931672,  2.00015059,  0.86821868,  2.04921444]])

In [111]:
arr.sort(axis=1)
arr

array([[-1.5552042 , -1.45328074, -1.27906299, -0.9387164 ],
       [-0.84527859, -0.68498917, -0.00942674,  0.14583788],
       [-0.77396206, -0.19950556,  0.03953923,  0.18727773],
       [-0.1970348 ,  0.09834803,  0.38459922,  0.51258435],
       [ 0.86821868,  1.09931672,  2.00015059,  2.04921444]])

In [112]:
arr = np.array([3,3,3,2,2,1,4,3,2])
np.unique(arr)

array([1, 2, 3, 4])

In [113]:
np.union1d(arr, [2,3,6])

array([1, 2, 3, 4, 6])

In [114]:
np.intersect1d(arr, [2,3,6])

array([2, 3])

In [115]:
np.setdiff1d(arr, [2,3,6])

array([1, 4])

## linear algebra

In [119]:
x = np.array( [[1,2,4], [5,6,7]] )
x.shape

(2, 3)

In [121]:
y = np.array( [[6,13], [5,6], [3,1]])
y.shape

(3, 2)

In [122]:
x*y

ValueError: ignored

In [124]:
z = x.dot(y)
z

array([[ 28,  29],
       [ 81, 108]])

In [126]:
zi = np.linalg.inv(z)
zi

array([[ 0.16      , -0.04296296],
       [-0.12      ,  0.04148148]])

In [127]:
z*zi

array([[ 4.48      , -1.24592593],
       [-9.72      ,  4.48      ]])

In [129]:
zi*z

array([[ 4.48      , -1.24592593],
       [-9.72      ,  4.48      ]])

In [130]:
zi.dot(z)

array([[ 1.00000000e+00, -1.19348975e-15],
       [-6.24500451e-17,  1.00000000e+00]])

In [133]:
arr = np.identity(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## random generation

In [134]:
np.random.normal(size=(4,4))

array([[-0.9225117 , -1.29646563,  0.27517169,  1.3834271 ],
       [ 0.08881508, -0.32272903, -1.00390208, -1.45400997],
       [ 0.03183654,  0.23950319,  0.82359625, -0.78595741],
       [-0.01685363, -0.01004187,  0.5066893 ,  2.11832146]])

In [135]:
np.random.seed(12345)
np.random.normal(size=(4,4))

array([[-0.20470766,  0.47894334, -0.51943872, -0.5557303 ],
       [ 1.96578057,  1.39340583,  0.09290788,  0.28174615],
       [ 0.76902257,  1.24643474,  1.00718936, -1.29622111],
       [ 0.27499163,  0.22891288,  1.35291684,  0.88642934]])

In [136]:
np.random.randint(0,1000,10)

array([387, 764, 124, 645, 143, 631, 843, 910, 371, 337])

In [137]:
np.random.randn(4,4)

array([[ 1.05962632e+00,  6.44448170e-01, -7.79917587e-03,
        -4.49203547e-01],
       [ 2.44896272e+00,  6.67226190e-01,  8.02925512e-01,
         5.75720851e-01],
       [ 1.38191821e+00,  9.92381398e-04, -1.43492473e-01,
        -2.06281745e-01],
       [-2.22392153e-01, -1.68240338e+00,  1.81165938e+00,
        -3.51305407e-01]])