<a href="https://colab.research.google.com/github/woodstone10/python-study/blob/main/Pandas_study2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

## numpy and pandas

In [ ]:
arr = np.array([4, 7, -5, 3])
arr

array([ 4,  7, -5,  3])

In [ ]:
s = pd.Series([4, 7, -5, 3])
s

0    4
1    7
2   -5
3    3
dtype: int64

In [ ]:
arr[2]

-5

In [ ]:
s[2]

-5

In [ ]:
s = pd.Series([4, 7, -5, 3], index=['a','b','c','d'])
s

a    4
b    7
c   -5
d    3
dtype: int64

In [ ]:
s[2]

-5

In [ ]:
s['c']

-5

In [ ]:
s*2

a     8
b    14
c   -10
d     6
dtype: int64

In [ ]:
s[s>3]

a    4
b    7
dtype: int64

In [ ]:
arr[arr>3]

array([4, 7])

In [ ]:
s

a    4
b    7
c   -5
d    3
dtype: int64

In [ ]:
np.sum(s)

9

In [ ]:
np.mean(s)

2.25

In [ ]:
data = {'state':['NY','NJ','CA','OH'],
      'city':['new york','morristown','san diego','chicago'],
      'value':[1, 2, 3, 4]}
data 

{'city': ['new york', 'morristown', 'san diego', 'chicago'],
 'state': ['NY', 'NJ', 'CA', 'OH'],
 'value': [1, 2, 3, 4]}

## data frame, ['columns'] or .loc[# of index]

In [ ]:
df = pd.DataFrame(data)
df

state        city  value
0    NY    new york      1
1    NJ  morristown      2
2    CA   san diego      3
3    OH     chicago      4

In [ ]:
df['state'] #from column

0    NY
1    NJ
2    CA
3    OH
Name: state, dtype: object

In [ ]:
df['city']

0      new york
1    morristown
2     san diego
3       chicago
Name: city, dtype: object

In [ ]:
df.city

0      new york
1    morristown
2     san diego
3       chicago
Name: city, dtype: object

In [ ]:
df.loc[0] #from index

state          NY
city     new york
value           1
Name: 0, dtype: object

In [ ]:
df = pd.DataFrame({'state':['NY','NJ','CA','OH'],
      'city':['new york','morristown','san diego','chicago'],
      'value':[1, 2, 3, 4]},
      index=['one','two','three','four'])
df

state        city  value
one      NY    new york      1
two      NJ  morristown      2
three    CA   san diego      3
four     OH     chicago      4

In [ ]:
df.columns

Index(['state', 'city', 'value'], dtype='object')

In [ ]:
df.index

Index(['one', 'two', 'three', 'four'], dtype='object')

In [ ]:
df.loc['three']

state           CA
city     san diego
value            3
Name: three, dtype: object

In [ ]:
df = pd.DataFrame({'state':['NY','NJ','CA','OH'],
      'city':['new york','morristown','san diego','chicago'],
      'value':[1, 2, 3, 4]},
      index=['one','two','three','four'],
      columns=['state','city','values','value','add'])
df

state        city values  value  add
one      NY    new york    NaN      1  NaN
two      NJ  morristown    NaN      2  NaN
three    CA   san diego    NaN      3  NaN
four     OH     chicago    NaN      4  NaN

In [ ]:
df['add']=2
df

state        city values  value  add
one      NY    new york    NaN      1    2
two      NJ  morristown    NaN      2    2
three    CA   san diego    NaN      3    2
four     OH     chicago    NaN      4    2

In [ ]:
df['add']=np.arange(4)
df

state        city values  value  add
one      NY    new york    NaN      1    0
two      NJ  morristown    NaN      2    1
three    CA   san diego    NaN      3    2
four     OH     chicago    NaN      4    3

In [ ]:
df.values #pandas dataframe -> numpy array

array([['NY', 'new york', nan, 1, 0],
       ['NJ', 'morristown', nan, 2, 1],
       ['CA', 'san diego', nan, 3, 2],
       ['OH', 'chicago', nan, 4, 3]], dtype=object)

In [ ]:
s

a    4
b    7
c   -5
d    3
dtype: int64

In [ ]:
s2 = s.reindex(['b','a','d','c'])
s2

b    7
a    4
d    3
c   -5
dtype: int64

In [ ]:
s

a    4
b    7
c   -5
d    3
dtype: int64

In [ ]:
s3 = pd.Series(s.values, index=[0,3,5,9])
s3

0    4
3    7
5   -5
9    3
dtype: int64

## reindex

In [ ]:
s3.reindex(range(15))

0     4.0
1     NaN
2     NaN
3     7.0
4     NaN
5    -5.0
6     NaN
7     NaN
8     NaN
9     3.0
10    NaN
11    NaN
12    NaN
13    NaN
14    NaN
dtype: float64

In [ ]:
s3.reindex(range(15), method='ffill')

0     4
1     4
2     4
3     7
4     7
5    -5
6    -5
7    -5
8    -5
9     3
10    3
11    3
12    3
13    3
14    3
dtype: int64

In [ ]:
s3.reindex(range(15), method='bfill')

0     4.0
1     7.0
2     7.0
3     7.0
4    -5.0
5    -5.0
6     3.0
7     3.0
8     3.0
9     3.0
10    NaN
11    NaN
12    NaN
13    NaN
14    NaN
dtype: float64

In [ ]:
s3.reindex(range(15), fill_value=0)

0     4
1     0
2     0
3     7
4     0
5    -5
6     0
7     0
8     0
9     3
10    0
11    0
12    0
13    0
14    0
dtype: int64

In [ ]:
df

state        city values  value  add
one      NY    new york    NaN      1    0
two      NJ  morristown    NaN      2    1
three    CA   san diego    NaN      3    2
four     OH     chicago    NaN      4    3

In [ ]:
df.reindex(columns=['city','state','value','add'])

city state  value  add
one      new york    NY      1    0
two    morristown    NJ      2    1
three   san diego    CA      3    2
four      chicago    OH      4    3

In [ ]:
s

a    4
b    7
c   -5
d    3
dtype: int64

In [ ]:
s[1]

7

In [ ]:
s['b']

7

In [ ]:
s['b':'c']

b    7
c   -5
dtype: int64

In [ ]:
s[1:3]

b    7
c   -5
dtype: int64

In [ ]:
s[s<5]

a    4
c   -5
d    3
dtype: int64

## drop

In [ ]:
s.drop('c')

a    4
b    7
d    3
dtype: int64

In [ ]:
s.drop(['b','d'])

a    4
c   -5
dtype: int64

In [ ]:
df

state        city values  value  add
one      NY    new york    NaN      1    0
two      NJ  morristown    NaN      2    1
three    CA   san diego    NaN      3    2
four     OH     chicago    NaN      4    3

In [ ]:
df.drop(['one'])

state        city values  value  add
two      NJ  morristown    NaN      2    1
three    CA   san diego    NaN      3    2
four     OH     chicago    NaN      4    3

In [ ]:
df.drop(['state'])

KeyError: ignored

In [ ]:
df.drop(['state'], axis=1)

city values  value  add
one      new york    NaN      1    0
two    morristown    NaN      2    1
three   san diego    NaN      3    2
four      chicago    NaN      4    3

In [ ]:
df.drop('values', axis='columns')

state        city  value  add
one      NY    new york      1    0
two      NJ  morristown      2    1
three    CA   san diego      3    2
four     OH     chicago      4    3

## calculation

In [ ]:
df1 = pd.DataFrame(np.arange(9).reshape(3,3))
df1

0  1  2
0  0  1  2
1  3  4  5
2  6  7  8

In [ ]:
df2 = pd.DataFrame(np.arange(12).reshape(4,3))
df2

0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [ ]:
df1+df2

0     1     2
0   0.0   2.0   4.0
1   6.0   8.0  10.0
2  12.0  14.0  16.0
3   NaN   NaN   NaN

In [ ]:
df1.add(df2)

0     1     2
0   0.0   2.0   4.0
1   6.0   8.0  10.0
2  12.0  14.0  16.0
3   NaN   NaN   NaN

In [ ]:
df1.add(df2, fill_value=0)

0     1     2
0   0.0   2.0   4.0
1   6.0   8.0  10.0
2  12.0  14.0  16.0
3   9.0  10.0  11.0

In [ ]:
df1.values

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
df1.values + df2.values

ValueError: ignored

In [ ]:
df1.values.add(df2.values)

AttributeError: ignored

In [ ]:
s

a    4
b    7
c   -5
d    3
dtype: int64

In [ ]:
df2

0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [ ]:
s + df2

0   1   2   a   b   c   d
0 NaN NaN NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN NaN NaN

In [ ]:
s.add(df2)

0   1   2   a   b   c   d
0 NaN NaN NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN NaN NaN

In [ ]:
df2.add(s, fill_value=0)

NotImplementedError: ignored

In [ ]:
s

a    4
b    7
c   -5
d    3
dtype: int64

In [ ]:
s.reindex(range(4))

0   NaN
1   NaN
2   NaN
3   NaN
dtype: float64

In [ ]:
s.reindex(index=[0,1,2,3])

0   NaN
1   NaN
2   NaN
3   NaN
dtype: float64

In [ ]:
s = pd.Series([4, 7, -5, 3], index=range(4))
s

0    4
1    7
2   -5
3    3
dtype: int64

In [ ]:
s + df2[0]

0     4
1    10
2     1
3    12
dtype: int64

In [ ]:
s.add(df2[0])

0     4
1    10
2     1
3    12
dtype: int64

## apply

In [ ]:
df

state        city values  value  add
one      NY    new york    NaN      1    0
two      NJ  morristown    NaN      2    1
three    CA   san diego    NaN      3    2
four     OH     chicago    NaN      4    3

In [ ]:
s

0    4
1    7
2   -5
3    3
dtype: int64

In [ ]:
np.abs(s)

0    4
1    7
2    5
3    3
dtype: int64

In [ ]:
df1

0  1  2
0  0  1  2
1  3  4  5
2  6  7  8

In [ ]:
df2

0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [ ]:
f = lambda x: x.max() - x.min()
df2.apply(f)

0    9
1    9
2    9
dtype: int64

In [ ]:
df2.apply(f, axis=1)

0    2
1    2
2    2
3    2
dtype: int64

In [ ]:
df2

0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [ ]:
def f1(x):
  return pd.Series([x.min(), x.max()], index=['min','max'])
df2.apply(f1)

0   1   2
min  0   1   2
max  9  10  11

In [ ]:
df2.apply(f1, axis=1)

min  max
0    0    2
1    3    5
2    6    8
3    9   11

In [ ]:
s

0    4
1    7
2   -5
3    3
dtype: int64

## sort

In [ ]:
s2 = s.reindex([0,2,1,3])
s2

0    4
2   -5
1    7
3    3
dtype: int64

In [ ]:
s2.sort_index()

0    4
1    7
2   -5
3    3
dtype: int64

In [ ]:
s2.sort_values()

2   -5
3    3
0    4
1    7
dtype: int64

In [ ]:
df2

0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [ ]:
df22 = df2.reindex([0, 2, 1, 3])
df22

0   1   2
0  0   1   2
2  6   7   8
1  3   4   5
3  9  10  11

In [ ]:
df22.sort_values(by=2)

0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [ ]:
df22.sort_values(by=2, ascending=False)

0   1   2
3  9  10  11
2  6   7   8
1  3   4   5
0  0   1   2

In [ ]:
df22.sort_values(by=2, axis=1, ascending=False)

2   1  0
0   2   1  0
2   8   7  6
1   5   4  3
3  11  10  9

## rank

In [ ]:
s

0    4
1    7
2   -5
3    3
dtype: int64

In [ ]:
s.rank()

0    3.0
1    4.0
2    1.0
3    2.0
dtype: float64

In [ ]:
df2

0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11